#!/bin/sh
set -e

if [ "$1" = "configure" ]
then
  groupadd -r futurehome || true
  groupadd -r thingsplex_service_template || true

  useradd -r -N -M -d / -s /bin/false -g thingsplex_service_template tithingsplex_service_templatebber || true

  chown -R thingsplex_service_template:futurehome /var/log/futurehome/thingsplex_service_template/ || true
  chown -R thingsplex_service_template:thingsplex_service_template /var/lib/futurehome/thingsplex_service_template/ || true
fi

deb-systemd-helper unmask thingsplex_service_template.service >/dev/null || true

if deb-systemd-helper --quiet was-enabled thingsplex_service_template.service; then
  deb-systemd-helper enable thingsplex_service_template.service >/dev/null || true
else
  deb-systemd-helper update-state thingsplex_service_template.service >/dev/null || true
fi

if [ -d /run/systemd/system ]; then
  systemctl --system daemon-reload >/dev/null || true

  if [ -n "$2" ]; then
    deb-systemd-invoke try-restart thingsplex_service_template.service >/dev/null || true
  else
    deb-systemd-invoke start thingsplex_service_template.service >/dev/null || true
  fi
fi